# Makefile for GEMMA build. This makefile is called from the GEMMA
# source tree and builds a library. Release/debug mode is handled
# from the calling makefile

D_COMPILER=ldc2
BIOD_INCLUDE=./BioD  # path to BioD source tree

DFLAGS = -Isource -I$(BIOD_INCLUDE) -wi -g -relocation-model=pic

ifndef GUIX
  ifdef GUIX_ENVIRONMENT
    GUIX=$(GUIX_ENVIRONMENT)
  endif
endif
ifdef GUIX
  LIBRARY_PATH=$(GUIX)/lib
endif

DLIBS       = $(LIBRARY_PATH)/libphobos2-ldc.a $(LIBRARY_PATH)/libdruntime-ldc.a
DLIBS_DEBUG = $(LIBRARY_PATH)/libphobos2-ldc-debug.a $(LIBRARY_PATH)/libdruntime-ldc-debug.a

SRC         = $(wildcard source/gemma/*.d) $(BIOD_INCLUDE)/bio/core/decompress.d $(BIOD_INCLUDE)/bio/std/range/splitter.d \
              $(BIOD_INCLUDE)/bio/std/genotype/maf.d \
              $(BIOD_INCLUDE)/bio/std/genotype/snp.d
OBJ         = $(SRC:.d=.o)
LIB         = libfaster-lmm-d.a # build a library

debug:          DFLAGS += -unittest -O0 -d-debug -link-debuglib
release static: DFLAGS += -O3 -release -enable-inlining -boundscheck=off
static:         DFLAGS += -static -L-Bstatic

all: debug

default: all

default debug release static: $(LIB)

source/gemma/api.o: source/gemma/kinship.o

%.o: %.d
	$(D_COMPILER) $(DFLAGS) -c $< -od=$(dir $@)

$(LIB): $(OBJ)
	$(info linking...)
	$(D_COMPILER) -lib $(DFLAGS) $(OBJ)
	ar rvs $(LIB) $(OBJ)

clean:
	rm -vf $(OBJ)
	rm -v $(LIB)
	rm -vf *.a
